### ISSUE TITLE
Rasterizer fails to initialize

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#120]
```
 + + + + + + + + + + + + + + + + + + + + + + +
                  Tectonicus
   Version: 2.28
   Build 452
   Constructed on September 29 2020 at 1249

   www.github.com/tectonicus/tectonicus  
 + + + + + + + + + + + + + + + + + + + + + + +
Started on Wed Sep 30 17:06:05 EDT 2020
System:
	OS Name: Linux
	OS Architecture: amd64
	OS Version: 4.18.0-193.19.1.el8_2.x86_64
	Java vendor: Oracle Corporation
	Java version: 1.8.0_265
	Awt toolkit: sun.awt.X11.XToolkit
Settings:
	loggingLevel:DEBUG
	mode:Command Line
	rasteriser:LWJGL
...
	colourDepth:16
	alphaBits:8
...
	forceLoadAwt:false
	logFile:/mnt/d7afb2aa-69c5-4151-9729-c6ed37bfd7c7/tectonicus/mc/Tectonicus/./TectonicusLog.txt
	outputHtmlName:map.html
	numDownsampleThreads:2
	singlePlayerName:

'My World Map' map
	worldDir: /home/turtle/working/tectonicus/world
	dimension: OVERWORLD
	cameraAngle: 45
	cameraElevation: 45
	closestZoomSize: 12
	worldSubset: FullWorldSubset
	useBiomeColours: false
	'Day' layer
		renderStyle: REGULAR
		lightStyle: Day
		imageFormat: Png
		customBlockConfig: 

Player skin cache is corrupt, cleaning...
Creating player icon assembler
Initialising display...
GLFW error: 0x00010007
java.lang.RuntimeException: Failed to create window!
	at tectonicus.rasteriser.lwjgl.LwjglRasteriser.<init>(Unknown Source)
	at tectonicus.rasteriser.RasteriserFactory.createRasteriser(Unknown Source)
	at tectonicus.TileRenderer.<init>(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
java.lang.RuntimeException: Could not create drawing surface
	at tectonicus.TileRenderer.<init>(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
Finished
```
I get the same GLFW error no matter what config.xml I use.  My normal one with multiple views as well as the most basic like this one:
```
<tectonicus version="2">
	<!-- Tweeks that you shouldn't need but work around quirks on some machines -->
	<tweeks
		force64BitNatives = "true"
	>
	</tweeks>
	<config
		outputDir="/home/turtle/working/MCMaps/an"
		numZoomLevels="8"
	/>

	<map
		name="My World Map"
		worldDir="/home/turtle/working/tectonicus/world"
		dimension="terra"
		closestZoomSize="12"
	>
		<layer
			name="Day"
			lighting="day"
			renderStyle="normal"
		/>
	</map>

</tectonicus>
```

I'm raising the issue to see if there is something specific I'm missing or if this is related to the removal of the lwjgl jars?

**Comment by skoeven** [comment]
I haven't tested this on Linux at all.  I'll see if I can take some time tomorrow and try it out on a headless box.

**Comment by skoeven** [comment]
So I've tested it on an Ubuntu Server docker image running Tectonicus and got a similar error to yours.  The box you're running on doesn't have a dedicated graphics card does it?  I believe this is an issue with GLFW not supporting software rendering out of the box.  As far as I know there's no convenient option to tell it to use software rendering like there was in LWGJ2.  It does have support for OSMesa but I think it needs to be compiled from source to enable that.  This is kind of unknown territory for me as I'm not much of a Linux guru but I'll see what I can figure out.

**Comment by turtle2472** [comment]
Thank you very much for looking into this.  While I'm normally a CentOS/RedHat guy I'd be willing to switch to almost any flavor of linux if it will work headlessly.  I don't want to designate a desktop for this given I cron the maps to update every 6 hours.

**Comment by skoeven** [comment]
I was able to get GLFW compiled with OSMesa support.  Still getting the same error in Tectonicus however.  So I need to do some experimenting to figure out what I'm missing.

**Comment by skoeven** [comment]
So good news, bad news and worse news.  The good news is that the version of GLFW included in LWJGL already supports OSMesa.  The bad news is that since it also supports X11 it still requires a display (so you still have to use xvfb, etc.).  The even worse news is that LWJGL can't find the OpenGL context when using GLFW with OSMesa.  I've tested it with both the LWJGL included GLFW and the version that I compiled myself with only OSMesa support.  The GLFW window is created successfully and has an OpenGL context, but LWJGL doesn't think that there is a current context and fails.  I'm going to create an issue for this over on the LWJGL project and see if they have any ideas.

**Comment by turtle2472** [comment]
:(

I really don't want to have to designate hardware to run the maps.  I think I can get away with it but that really taxes the system during the map renderings.

Thank you for continuing to plug away at this.  I really would like to be able to get this working.  Another idea is even if we end up with a Docker container that just runs the maps.  This would make it really simple to even throw up into something like Digital Ocean or the like.  I'm not that good with Docker right now, but I've dabbled with it some so I'm sure I could get better with it.

In the end, I think being able to script and fully automate on a headless VM is really the goal in my mind.

Again, thank you. :)

**Comment by skoeven** [comment]
I agree that getting Tectonicus to work on a headless VM is important. I view it as one of the main use cases for the software for many people.  That's how I first started using it back in 2012!  So on that front I have good news this time!  I added support for EGL as an alternative way to get an OpenGL context.  With this I was able to render my small test map without any issues using my Ubuntu Server Docker container.  This will be nice because it should allow headless rendering with and without a GPU (though I have currently only tested without a GPU).

For rendering without a GPU you still need to use xvfb or a vnc server in order to create a display.  I've tested both methods and they both work.  LWJGL does not supply an EGL native library so you have to manually install that (I think it's 'mesa-libEGL' on CentOS 8).  To use EGL, add the attribute useEGL="true" to the rasteriser node in your xml config file (or run Tectonicus with the command line option --useEGL.  I'll update the documentation with this new option.

Also, I think creating a Docker container that does headless rendering with Tectonicus is a great idea.  Years ago I experimented with some Docker images that ran Tectonicus.  I think I could adapt some things from those and my current test container setup and possibly make something that other people could use for headless rendering without having to do a whole lot of setup themselves.

Anyway, let me know if the EGL stuff works for you.

**Comment by turtle2472** [comment]
That appears to be working so far!  It takes a long time to render my maps and I didn't think to just do a small subset.  However, it is going through the motions as expected.

I do have 27 errors like this one, but it is still processing:
```
Error while trying to load chunk at (48, 6) from region /home/turtle/working/tectonicus/world/region/r.1.0.mca
java.lang.NullPointerException
	at tectonicus.raw.RawChunk.init(Unknown Source)
	at tectonicus.raw.RawChunk.<init>(Unknown Source)
	at tectonicus.Chunk.loadRaw(Unknown Source)
	at tectonicus.Region.loadChunk(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
java.lang.NullPointerException
	at tectonicus.TileRenderer.findSigns(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
java.lang.NullPointerException
	at tectonicus.TileRenderer.findPortals(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
java.lang.NullPointerException
	at tectonicus.TileRenderer.findViews(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
java.lang.NullPointerException
	at tectonicus.TileRenderer.findChests(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
```

**Comment by turtle2472** [comment]
At the risk of drifting this issue, it failed to build my maps but the rasterizer portion seems usable now.
```
...
Outputted 19 beds
Writing portals...
Wrote 0 portals
Writing views...
Writing chests to /home/turtle/working/MCMaps/an/Map0/chests.js
Finding changed views...
Found 0 changed views (out of 0 total views)
Drawing Day views...
Drawing Night views...
View rendering done!
Creating block registry
Loading all block state and block model json files...
All json files loaded.
Tile cache directory found and is valid. Using cache at /home/turtle/working/MCMaps/an/Cache/tileHashes/Map0/LayerA
100%
FindChangedTiles took: 103.057 seconds
Render Base Tiles
Base render is at zoom 23 with 512x512 tiles
Error while trying to load chunk at (83, -5) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (82, -3) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (84, -3) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (85, -3) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (82, -4) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (84, -4) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (83, -2) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (84, -2) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (85, -2) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
Error while trying to load chunk at (86, -2) from region /home/turtle/working/tectonicus/world/region/r.2.-1.mca
java.lang.NullPointerException
java.lang.NullPointerException
        at tectonicus.Chunk.getBiomeId(Unknown Source)
        at tectonicus.world.World.getBiomeId(Unknown Source)
        at tectonicus.world.World.getWaterColor(Unknown Source)
        at tectonicus.blockTypes.Water.addEdgeGeometry(Unknown Source)
        at tectonicus.Chunk.createGeometry(Unknown Source)
        at tectonicus.world.World.draw(Unknown Source)
        at tectonicus.world.World.draw(Unknown Source)
        at tectonicus.TileRenderer.renderBaseTiles(Unknown Source)
        at tectonicus.TileRenderer.output(Unknown Source)
        at tectonicus.TectonicusApp.run(Unknown Source)
        at tectonicus.TectonicusApp.main(Unknown Source)
Cleaning up...
Writing player skin cache info (19 skins to write)
100%
Player skin cache written
Finished
./makemap_copy.sh: line 27:  3427 Segmentation fault      (core dumped) vncserver -kill :1```

I've done a few attempts and it fails during this part:
```
FindChangedTiles took: 118.741 seconds
Render Base Tiles
Base render is at zoom 23 with 512x512 tiles
Rendering tile @ 125,62 (tile 752 of 92234)
```

I can create a new issue if you'd like since this doesn't seem to be rasterizer specific.

**Comment by skoeven** [comment]
Yeah, if you wouldn't mind, go ahead and create a new issue.

**Comment by skoeven** [comment]
LWJGL has added support for using OSMesa OpenGL contexts: lwjgl/lwjgl3#595
Once this is released I'll add support for it to Tectonicus (see #125).  For now we have the EGL option for headless rendering that seems to be working well.

**Comment by micthiesen** [comment]
I am also having an issue initializing the rasterizer when running on a headless Linux server (inside Docker). I've set `useEGL=true`. At first the error was `java.lang.UnsatisfiedLinkError: Failed to locate library: libEGL.so.1` but I fixed that by:
1. Installing the `mesa-gl mesa-dev` Alpine packages
1. Setting the env var `CLASSPATH=/usr/lib/:$CLASSPATH`

But now I run into the following error and I'm not sure how to fix it:
```
Initialising display...
Using EGL for context creation.
java.lang.RuntimeException: EGL error: 12289
        at tectonicus.rasteriser.lwjgl.LwjglRasteriser.<init>(Unknown Source)
        at tectonicus.rasteriser.RasteriserFactory.createRasteriser(Unknown Source)
        at tectonicus.TileRenderer.<init>(Unknown Source)
        at tectonicus.TectonicusApp.run(Unknown Source)
        at tectonicus.TectonicusApp.main(Unknown Source)
java.lang.RuntimeException: Could not create drawing surface
        at tectonicus.TileRenderer.<init>(Unknown Source)
        at tectonicus.TectonicusApp.run(Unknown Source)
        at tectonicus.TectonicusApp.main(Unknown Source)
Finished
```

Any help would be appreciated. Alternatively if waiting for OSMesa support is necessary that's ok to. Thank you.

**Comment by skoeven** [comment]
It could be that it doesn't like the default pixel format Tectonicus uses to try and create the EGL context.  I'm a little low on spare time right now but I'm hopeful that this one shouldn't be too hard to fix (famous last words).  Do you have a Dockerfile you could share or at least which base image you are using for your container?  That would be very helpful for testing.  As I can find the time I'll give it a try and see what I can figure out.

**Comment by micthiesen** [comment]
I'd appreciate that, thank you. But definitely don't feel obligated or rushed. My base image is `openjdk:8-jre-alpine` and here's my Dockerfile, although it's fairly specific to my server (e.g. getting the Minecraft jar from a specific folder):
```Dockerfile
FROM openjdk:8-jre-alpine

RUN apk add curl unzip mesa-gl mesa-dev

ENV CLASSPATH /usr/lib/:$CLASSPATH

RUN curl -s https://api.github.com/repos/tectonicus/tectonicus/releases/latest \
  | grep 'browser_download_url.*zip"' \
  | cut -d : -f 2,3 \
  | tr -d \" \
  | xargs -n 1 curl -O -sSL
RUN unzip Tectonicus-*.zip
RUN rm -f Tectonicus-*.zip
RUN mv /Tectonicus-* /Tectonicus

COPY ./data/cache/* /jar-cache/
RUN mv $(ls /jar-cache/mojang* | tail -1) /minecraft.jar
RUN rm -fr /jar-cache

COPY ./config_tectonicus.xml /config_tectonicus.xml

CMD /Tectonicus/bin/tectonicus --config=/config_tectonicus.xml
```

**Comment by micthiesen** [comment]
And `config_tectonicus.xml` is:
```xml
<?xml version="1.0"?>
<tectonicus version="2">
  <config outputDir="/public" minecraftJar="/minecraft.jar" />
  <rasteriser useEGL="true" />

  <map name="Overworld" worldDir="/server/world/level.dat" useCache="true" cacheDir="/cache">
    <layer name="Day" lighting="day" />
  </map>
</tectonicus>
```
