### ISSUE TITLE
Probably missing mod texture caused NPE (NullPointerException) Minecraft 1.16.4 + mods + Tectonicus 2.28.7

### ISSUE THREAD

**Issue by mjevans** [tectonicus/tectonicus#135]
I've tested this with both the latest public release and a locally compiled version of the current (as of this bug report) HEAD ( 051b012174b0a812fdb2368c625fc7ebed158fac )

Missing mod block texture leads to NPE?

Minecraft 1.16.4 https://www.curseforge.com/minecraft/modpacks/valhelsia-3 (pre7-3.1.0)

Unless 1.16.4 is close enough to 1.17 that it is a dup of report #130 

The log level is set to ALL, I did add all of the ./mods/ jar files as mods in the list for each world section.  It appears to crash while trying to render the very first chunk, which happens to have two mod blocks exposed:

forbidden_arcanus:darkstone
mekanism:copper_ore

Expected behavior: Render nothing (clear/transparent), minecraft:stone, or that purple and black no-texture placeholder?

I think my config.xml is correct, and it includes this for headless ( #120 )

        <rasteriser
                useEGL="true"

xvfb-run -a \
        java -Xms1G -Xmx2G \
        -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true \
        -Dorg.lwjgl.opengl.Display.noinput=true \
        -jar lib/Tectonicus-2.28.7.jar \
        config=config.xml
...
Render Base Tiles
Base render is at zoom 12 with 512x512 tiles
Unable to find forbidden_arcanus:darkstone block in registry. World.Location(coord=[ChunkCoord (-8, -2) / <-8, -2> ], x=0, y=1, z=2), Region file: r.-1.-1.mca
Unable to find forbidden_arcanus:darkstone block in registry. World.Location(coord=[ChunkCoord (-8, -2) / <-8, -2> ], x=0, y=1, z=10), Region file: r.-1.-1.mca
Unable to find forbidden_arcanus:darkstone block in registry. World.Location(coord=[ChunkCoord (-8, -2) / <-8, -2> ], x=0, y=1, z=12), Region file: r.-1.-1.mca
Unable to find forbidden_arcanus:darkstone block in registry. World.Location(coord=[ChunkCoord (-8, -2) / <-8, -2> ], x=1, y=1, z=6), Region file: r.-1.-1.mca
Unable to find forbidden_arcanus:darkstone block in registry. World.Location(coord=[ChunkCoord (-8, -2) / <-8, -2> ], x=8, y=1, z=6), Region file: r.-1.-1.mca
Unable to find forbidden_arcanus:darkstone block in registry. World.Location(coord=[ChunkCoord (-8, -2) / <-8, -2> ], x=9, y=1, z=6), Region file: r.-1.-1.mca
Unable to find forbidden_arcanus:darkstone block in registry. World.Location(coord=[ChunkCoord (-8, -2) / <-8, -2> ], x=10, y=1, z=6), Region file: r.-1.-1.mca
Unable to find mekanism:copper_ore block in registry. World.Location(coord=[ChunkCoord (-8, -2) / <-8, -2> ], x=15, y=1, z=2), Region file: r.-1.-1.mca
java.lang.NullPointerException
        at tectonicus.Chunk.createGeometry(Unknown Source)
        at tectonicus.world.World.draw(Unknown Source)
        at tectonicus.world.World.draw(Unknown Source)
        at tectonicus.TileRenderer.renderBaseTiles(Unknown Source)
        at tectonicus.TileRenderer.output(Unknown Source)
        at tectonicus.TectonicusApp.run(Unknown Source)
        at tectonicus.TectonicusApp.main(Unknown Source)
Cleaning up...

**Comment by skoeven** [comment]
Normally Tectonicus should ignore blocks that it doesn't recognize, but there must be an issue with the mod support.  I haven't tested the mod support at all since I implemented support for the Minecraft 1.13 block format, so there could easily be something broken.  I'll add this to my to-do backlog.

**Comment by mjevans** [comment]
Thank you.

I wanted to also test out some extra guards for null in my local code, but spent a couple hours trying to figure out how to get source code line numbers to show up in the debugging statements.  log4j2 is seemingly beyond me, or there's some java quirk that is infuriatingly difficult to search for given all of the other hits about debugging the build process (gradle / maven) instead.

If your project has some way of enabling / being run so that it generates the line numbers for the faults it would help.

I'm building it (on linux) via: $ sh gradlew build --warning-mode all ; which yields an artifact build/distributions/Tectonicus-${version}.zip

**Comment by skoeven** [comment]
If you change options.debug from false to true in the build.gradle file (line 19) and rebuild you should get line numbers in stack traces.

**Comment by mjevans** [comment]
While re-testing I noticed something that was much easier to spot then on the same day I was trying to set everything up (due to the involved timestamps suddenly being much more obviously wrong). I had overlooked that everything was packed up within a subdirectory and given it was a .zip file rather than a .tar.xz my usual habit of including a verbose file list wasn't part of the extraction command.

As a co-incidence I also included the function-level only patch, one or both of these extra guards for null solved my issue.

diff --git a/src/main/java/tectonicus/Chunk.java b/src/main/java/tectonicus/Chunk.java
index f439394..b4a5493 100644
--- a/src/main/java/tectonicus/Chunk.java
+++ b/src/main/java/tectonicus/Chunk.java
@@ -134,7 +134,9 @@ public class Chunk
                                                                //TODO: This is quite slow. Need to profile and figure out if it can be sped up
                                                                List<BlockStateModel> models;
                                                                BlockStateWrapper stateWrapper = modelRegistry.getBlock(blockName);
+                                                               if (null == stateWrapper) { continue ; }
                                                                models = stateWrapper.getModels(properties);
+                                                               if (null == models) { continue ; }
 
                                                                for (BlockStateModel model : models) {
                                                                        model.createGeometry(x, y, z, world, rawChunk, geometry);

I'm not sure that would be the final commit though; it might be nice to have the option of falling back to a default renderer if none is found. (E.G. lookup this other block instead.)

**Comment by mjevans** [comment]
diff --git a/src/main/java/tectonicus/Chunk.java b/src/main/java/tectonicus/Chunk.java
    index f439394..b4a5493 100644
    --- a/src/main/java/tectonicus/Chunk.java
    +++ b/src/main/java/tectonicus/Chunk.java
    @@ -134,7 +134,9 @@ public class Chunk
                                                                    //TODO: This is quite slow. Need to profile and figure out if it can be sped up
                                                                    List<BlockStateModel> models;
                                                                    BlockStateWrapper stateWrapper = modelRegistry.getBlock(blockName);
    +                                                               if (null == stateWrapper) { continue ; }
                                                                    models = stateWrapper.getModels(properties);
    +                                                               if (null == models) { continue ; }
    
                                                                    for (BlockStateModel model : models) {
                                                                            model.createGeometry(x, y, z, world, rawChunk, geometry);

**Comment by mjevans** [comment]
I was able to test this again today with the debug build.

Of note, I had both of my patches commented out, but sitll in the Chunk.jar file...

models = stateWrapper.getModels(properties); // Line 138 in in the build beneath.
//FIXME: if (null == models) { continue; }

java.lang.NullPointerException
        at tectonicus.Chunk.createGeometry(Chunk.java:138)
        at tectonicus.world.World.draw(World.java:626)
        at tectonicus.world.World.draw(World.java:573)
        at tectonicus.TileRenderer.renderBaseTiles(TileRenderer.java:715)
        at tectonicus.TileRenderer.output(TileRenderer.java:318)
        at tectonicus.TectonicusApp.run(TectonicusApp.java:165)
        at tectonicus.TectonicusApp.main(TectonicusApp.java:342)

PS

The TODO above in the source code, is createGeometry reusing every asset it can?  Already included textures, models (though that might be a Vulkan thing) etc?

**Comment by mjevans** [comment]
Re-tested with this and only the first of my two null-checks was necessary.

							} else {
								//TODO: This is quite slow. Need to profile and figure out if it can be sped up
								List<BlockStateModel> models;
								BlockStateWrapper stateWrapper = modelRegistry.getBlock(blockName);
								if (null == stateWrapper) { continue; }
								models = stateWrapper.getModels(properties);
								// if (null == models) { continue; }
