### ISSUE TITLE
Repeatable out of memory errors

### ISSUE THREAD

**Issue by skoeven** [tectonicus/tectonicus#16]
_From [steveme...@gmail.com](https://code.google.com/u/116845111042319609972/) on September 15, 2012 13:46:18_

What steps will reproduce the problem? 1. Windows 7 Professional 64-bit, all updates applied, 6G RAM, 736G free drive space, Java 64-bit build 1.6.0_35-b10.  Tectonicus 2.14, Minecraft 1.3.2 (though the same issue started while I was using Minecraft 1.2.5.)  
2. Erase all previous Tectonicus output.
3. Use either of the the myconfig.xml files attached.  (myconfig2 is cleaner, I think.)
4. Use this command line:  
     java -Xms2048m -Xmx4096m -jar Tectonicus_v2.14.jar config=myconfig2.xml
5. Uninstalling all Java versions and re-installing only the latest version 6 Java does not help.
6. Referencing a modded minecraft.jar and an unmodded one makes no difference. What is the expected output? What do you see instead? Please attach a full log file. In the past, when I had Minecraft 1.2.5, the Tectonicus would generate about 14G of files and a usable map from about 32,000 tiles (if memory serves).  During that time it started crashing during rendering, randomly between 3000 and 10000 tiles with this error message:
# 

java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Unknown Source)
        at java.nio.DirectByteBuffer.<init>(Unknown Source)
        at java.nio.ByteBuffer.allocateDirect(Unknown Source)
        at org.lwjgl.BufferUtils.createByteBuffer(BufferUtils.java:60)
        at org.lwjgl.BufferUtils.createFloatBuffer(BufferUtils.java:110)
        at tectonicus.rasteriser.lwjgl.LwjglMesh.realloc(LwjglMesh.java:250)
        at tectonicus.rasteriser.lwjgl.LwjglMesh.addVertex(LwjglMesh.java:91)
        at tectonicus.rasteriser.MeshUtil.addQuad(MeshUtil.java:110)
        at tectonicus.blockTypes.Water.addEdgeGeometry(Water.java:161)
        at tectonicus.blockTypes.Water.addInteriorGeometry(Water.java:85)
        at tectonicus.Chunk.createGeometry(Chunk.java:151)
        at tectonicus.world.World.draw(World.java:535)
        at tectonicus.world.World.draw(World.java:482)
        at tectonicus.TileRenderer.renderBaseTiles(TileRenderer.java:676)
        at tectonicus.TileRenderer.output(TileRenderer.java:321)
        at tectonicus.TectonicusApp.run(TectonicusApp.java:952)
        at tectonicus.TectonicusApp.main(TectonicusApp.java:1212)
======================================================================= What version of the product are you using? What is your operating system and Java version? See above. Please provide any additional information below. The only think I can think of that's changed during this time is my video card.  I was using an nVidia 8800GTS, and now I have an nVidia GTX 560 Ti.

Thanks.

**Attachment:** [TectonicusLog.txt myconfig2.xml myconfig.xml](http://code.google.com/p/tectonicus/issues/detail?id=16)

_Original issue: http://code.google.com/p/tectonicus/issues/detail?id=16_

**Comment by skoeven** [comment]
This may not be as much of an issue with modern machines and modern Java versions.  Closing.
