### ISSUE TITLE
NullPointerException When rendering 1.11 world

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#84]
```
Settings changed! Deleting tile cache at /Volumes/Ant/MCMaps/an/Cache/tileHashes/Map0/LayerA
New tile cache will be created for this render
100%
FindChangedTiles took: 104.882 seconds
RenderBaseTiles
Base render is at zoom 23 with 512x512 tiles
RenderBaseTiles
java.lang.NullPointerException of 139316)
	at tectonicus.blockTypes.Skull.addEdgeGeometry(Unknown Source)
	at tectonicus.blockTypes.Skull.addInteriorGeometry(Unknown Source)
	at tectonicus.Chunk.createGeometry(Unknown Source)
	at tectonicus.world.World.draw(Unknown Source)
	at tectonicus.world.World.draw(Unknown Source)
	at tectonicus.TileRenderer.renderBaseTiles(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
Cleaning up...
Writing player skin cache info (12 skins to write)
100%
Player skin cache written
Finished
```

```
 + + + + + + + + + + + + + + + + + + + + + + +
                  Tectonicus
   Version: null
   Build null
   Constructed on null at null
 + + + + + + + + + + + + + + + + + + + + + + +
Started on Sun Jan 01 19:48:05 EST 2017
System:
	OS Name: Mac OS X
	OS Architecture: x86_64
	OS Version: 10.12.2
	Java vendor: Oracle Corporation
	Java version: 1.8.0_111
	Awt toolkit: sun.lwawt.macosx.LWCToolkit
	Headless?: null
Settings:
	mode:CommandLine
	rasteriser:Lwjgl
```

So I tried rendering with our normal custom resource pack as well as letting it use the default MC pack.  No matter how I do it the map fails to render with the same result indicated at the top.

**Comment by turtle2472** [comment]
So I went and did more testing and isolating and it is definitely something with the skulls/heads.  I only tried with the creeper, zombie, skeleton and wither skeleton heads though so I don't know if others are just as impacted.  I placed each one down in a subset that didn't have a skull in it and would process normally.  Once the skull was placed the rendering failed.  Any or all of the skulls listed above resulted in failed rendering.

I also upgraded our world to 1.11.2 in hopes bug fixes in that version related to the skulls might fix the issue here but it didn't.  Here are the logs of the good rendering without a skull and one still failing with a skull.  I did try with both our custom resource pack as well as MC's default and that made no difference.

Let me know if you need more details or other testing I can do for you.

This is a successful rendering:
```
Parsing config from /Users/Me/Dropbox/mc/Tectonicus/onewaybase.xml
 + + + + + + + + + + + + + + + + + + + + + + +
                  Tectonicus
   Version: null
   Build null
   Constructed on null at null
 + + + + + + + + + + + + + + + + + + + + + + +
Started on Mon Jan 02 14:28:39 EST 2017
System:
	OS Name: Mac OS X
	OS Architecture: x86_64
	OS Version: 10.12.2
	Java vendor: Oracle Corporation
	Java version: 1.8.0_111
	Awt toolkit: sun.lwawt.macosx.LWCToolkit
	Headless?: null
Settings:
	mode:CommandLine
	rasteriser:Lwjgl
	outputDir:/Volumes/Ant/MCMaps/an
	useCache:true
	cacheDir:/Volumes/Ant/MCMaps/an/Cache
	minecraftJar:/Users/Me/Dropbox/mc/core/minecraft.jar
	texturePack:/Users/Me/Dropbox/mc/core/ANBTextures.zip
	colourDepth:32
	alphaBits:0
	numSamples:4
	tileSize:512
	numZoomLevels:7
	portalsInitiallyVisible:false
	showSpawn:true
	signsInitiallyVisible:false
	playersInitiallyVisible:true
	bedsInitiallyVisible:false
	spawnInitiallyVisible:true
	viewsInitiallyVisible:false
	eraseOutputDir:false
	extractLwjglNatives:true
	isVerbose:false
	forceLoadAwt:false
	force32BitNatives:false
	force64BitNatives:false
	logFile:/Users/Me/Dropbox/mc/Logs/Tectonicus.log
	outputHtmlName:index.html
	numDownsampleThreads:8
	singlePlayerName:

'North East' map
	worldDir: /Volumes/Ant/MCMaps/world
	dimension: Terra
	cameraAngle: 45
	cameraElevation: 35
	closestZoomSize: 23
	worldSubset: CircularWorldSubset (-200, -200) 200
	useBiomeColours: false
	'Day' layer
		renderStyle: Regular
		lightStyle: Day
		imageFormat: Jpg
		imageCompressionLevel: 0.75
		customBlockConfig: 

Using existing player skin cache
Creating player icon assembler
Initialising display...
	Drawable: null
	created pbuffer: org.lwjgl.opengl.Pbuffer@4f2410ac
	used pixel format:   colour:32 depth:24 alpha:0 stencil:0 samples:4
	display created ok
Using rasteriser: tectonicus.rasteriser.lwjgl.LwjglRasteriser@504bae78
 -- Lwjgl Rasteriser -- 
	LWJGL version: 2.9.3
	type: Offscreen
	width: 2048
	heigth: 2048
	pBuffer: org.lwjgl.opengl.Pbuffer@4f2410ac
	OpenGL Vendor: NVIDIA Corporation
	OpenGL Renderer: NVIDIA GeForce GTX 750 Ti OpenGL Engine
	OpenGL Version: 2.1 NVIDIA-10.15.20 367.15.10.25f01
Creating camera
TileRenderer init complete
StartingRenderer
Starting tile renderer
Loading world from base dir /Volumes/Ant/MCMaps/world with dimension Terra
	Full dimension dir: /Volumes/Ant/MCMaps/world
Loading level.dat
Loading textures
Creating block registry

The texture file 'assets/minecraft/textures/blocks/usb_charger_side.png' could not be found.
Error while parsing blockConfig element: [Solid: null]

Loading players
Loading players from /Volumes/Ant/MCMaps/world/playerdata
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/11fc9cfa6387e5cb7f22.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/4adb5dc9-3b03d3e37c9b.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/554a3177-2953bb1ce35f.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/8b9682be-0bfc6594aa04.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/93feb001-26920a55ee92.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/b7f7d4cd-5360feff6e52.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/bb25a760-a9af6ec96f75.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/c2a76ac8-ea18eab58f50.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/d4105151-36b848d6f8b1.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/e91fe2d6-f7dc8e96ea7b.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/eac3860d-c688557ff388.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/f3e6f39b-f6685b80eb77.dat
	loaded 12 players
Detected Anvil save format
CalculatingChunkHashes
Discovering chunks...
Looking for chunks in /Volumes/Ant/MCMaps/world
	found 3000 chunks so far
Found 3072 chunks in total
Found 0 views
Finding visible tiles...
FindVisibleTiles
100%
found 470 total tiles to output
Finding changed tiles since last render...
FindChangedTiles
Generating compass image...
Generating portal image...
Writing signs to /Volumes/Ant/MCMaps/an/Map0/signs.js
Outputting players to /Volumes/Ant/MCMaps/an/Map0/players.js
	outputting player1
	outputting turtle2472
Outputted 2 players
Outputting beds to /Volumes/Ant/MCMaps/an/Map0/beds.js
	outputting player1's bed
Outputted 1 beds
Writing portals...
Wrote 3 portals
Writing views...
Generating block image...
Writing chests to /Volumes/Ant/MCMaps/an/Map0/chests.js
Outputting block stats to /Volumes/Ant/MCMaps/an/Map0/blockStats.js
Outputted 287 block counts
Outputting world stats to /Volumes/Ant/MCMaps/an/Map0/worldStats.js
Outputted world stats
Finding changed views...
Found 0 changed views (out of 0 total views)
Drawing Day views...
Drawing Night views...
View rendering done!

The texture file 'assets/minecraft/textures/blocks/usb_charger_side.png' could not be found.
Error while parsing blockConfig element: [Solid: null]

Tile cache directory found and is valid. Using cache at /Volumes/Ant/MCMaps/an/Cache/tileHashes/Map0/LayerA
100%
FindChangedTiles took: 0.189 seconds
RenderBaseTiles
Base render is at zoom 23 with 512x512 tiles
RenderBaseTiles
Rendering tile @ 0,-3 (tile 97 of 97)))
Base tile render complete
Downsampling to create zoom level 6
Downsampling level 6
	Scanning for next zoom tiles...
	Downsampling 97 tiles into 30 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 5
Downsampling level 5
	Scanning for next zoom tiles...
	Downsampling 30 tiles into 10 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 4
Downsampling level 4
	Scanning for next zoom tiles...
	Downsampling 10 tiles into 6 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 3
Downsampling level 3
	Scanning for next zoom tiles...
	Downsampling 6 tiles into 4 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 2
Downsampling level 2
	Scanning for next zoom tiles...
	Downsampling 4 tiles into 2 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 1
Downsampling level 1
	Scanning for next zoom tiles...
	Downsampling 2 tiles into 2 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 0
Downsampling level 0
	Scanning for next zoom tiles...
	Downsampling 2 tiles into 2 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling took 0 seconds
Outputting world vectors to /Volumes/Ant/MCMaps/an/Map0/worldVectors.js
World vectors done
width: 256
height: 256
Outputting master contents to /Volumes/Ant/MCMaps/an/Scripts/contents.js
Exporting html...
OutputHtml
	writing html to /Volumes/Ant/MCMaps/an/index.html
Exporting stats...
Outputting stats to /Volumes/Ant/MCMaps/an/Scripts/stats.js
Writing changed file list...
OutputChangedList
Render complete - total time 21 seconds
Cleaning up...
Writing player skin cache info (12 skins to write)
100%
Player skin cache written
Finished
```

Now this one is with a skull placed, wither skeleton I believe:
```
Parsing config from /Users/Me/Dropbox/mc/Tectonicus/onewaybase.xml
 + + + + + + + + + + + + + + + + + + + + + + +
                  Tectonicus
   Version: null
   Build null
   Constructed on null at null
 + + + + + + + + + + + + + + + + + + + + + + +
Started on Mon Jan 02 14:20:21 EST 2017
System:
	OS Name: Mac OS X
	OS Architecture: x86_64
	OS Version: 10.12.2
	Java vendor: Oracle Corporation
	Java version: 1.8.0_111
	Awt toolkit: sun.lwawt.macosx.LWCToolkit
	Headless?: null
Settings:
	mode:CommandLine
	rasteriser:Lwjgl
	outputDir:/Volumes/Ant/MCMaps/an
	useCache:true
	cacheDir:/Volumes/Ant/MCMaps/an/Cache
	minecraftJar:/Users/Me/Dropbox/mc/core/minecraft.jar
	texturePack:/Users/Me/Dropbox/mc/core/ANBTextures.zip
	colourDepth:32
	alphaBits:0
	numSamples:4
	tileSize:512
	numZoomLevels:7
	portalsInitiallyVisible:false
	showSpawn:true
	signsInitiallyVisible:false
	playersInitiallyVisible:true
	bedsInitiallyVisible:false
	spawnInitiallyVisible:true
	viewsInitiallyVisible:false
	eraseOutputDir:false
	extractLwjglNatives:true
	isVerbose:false
	forceLoadAwt:false
	force32BitNatives:false
	force64BitNatives:false
	logFile:/Users/Me/Dropbox/mc/Logs/Tectonicus.log
	outputHtmlName:index.html
	numDownsampleThreads:8
	singlePlayerName:

'North East' map
	worldDir: /Volumes/Ant/MCMaps/world
	dimension: Terra
	cameraAngle: 45
	cameraElevation: 35
	closestZoomSize: 23
	worldSubset: CircularWorldSubset (-200, -200) 200
	useBiomeColours: false
	'Day' layer
		renderStyle: Regular
		lightStyle: Day
		imageFormat: Jpg
		imageCompressionLevel: 0.75
		customBlockConfig: 

Using existing player skin cache
Creating player icon assembler
Initialising display...
	Drawable: null
	created pbuffer: org.lwjgl.opengl.Pbuffer@4f2410ac
	used pixel format:   colour:32 depth:24 alpha:0 stencil:0 samples:4
	display created ok
Using rasteriser: tectonicus.rasteriser.lwjgl.LwjglRasteriser@504bae78
 -- Lwjgl Rasteriser -- 
	LWJGL version: 2.9.3
	type: Offscreen
	width: 2048
	heigth: 2048
	pBuffer: org.lwjgl.opengl.Pbuffer@4f2410ac
	OpenGL Vendor: NVIDIA Corporation
	OpenGL Renderer: NVIDIA GeForce GTX 750 Ti OpenGL Engine
	OpenGL Version: 2.1 NVIDIA-10.15.20 367.15.10.25f01
Creating camera
TileRenderer init complete
StartingRenderer
Starting tile renderer
Loading world from base dir /Volumes/Ant/MCMaps/world with dimension Terra
	Full dimension dir: /Volumes/Ant/MCMaps/world
Loading level.dat
Loading textures
Creating block registry

The texture file 'assets/minecraft/textures/blocks/usb_charger_side.png' could not be found.
Error while parsing blockConfig element: [Solid: null]

Loading players
Loading players from /Volumes/Ant/MCMaps/world/playerdata
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/11fc9cfa-6387e5cb7f22.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/4adb5dc9-3b03d3e37c9b.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/554a3177-2953bb1ce35f.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/8b9682be-0bfc6594aa04.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/93feb001-26920a55ee92.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/b7f7d4cd-5360feff6e52.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/bb25a760-a9af6ec96f75.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/c2a76ac8-ea18eab58f50.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/d4105151-36b848d6f8b1.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/e91fe2d6-f7dc8e96ea7b.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/eac3860d-c688557ff388.dat
Loading raw player from /Volumes/Ant/MCMaps/world/playerdata/f3e6f39b-f6685b80eb77.dat
	loaded 12 players
Detected Anvil save format
CalculatingChunkHashes
Discovering chunks...
Looking for chunks in /Volumes/Ant/MCMaps/world
	found 3000 chunks so far
Found 3072 chunks in total
Found 0 views
Finding visible tiles...
FindVisibleTiles
100%
found 470 total tiles to output
Finding changed tiles since last render...
FindChangedTiles
Generating compass image...
Generating portal image...
Writing signs to /Volumes/Ant/MCMaps/an/Map0/signs.js
Outputting players to /Volumes/Ant/MCMaps/an/Map0/players.js
	outputting player1
	outputting turtle2472
Outputted 2 players
Outputting beds to /Volumes/Ant/MCMaps/an/Map0/beds.js
	outputting player1's bed
Outputted 1 beds
Writing portals...
Wrote 3 portals
Writing views...
Generating block image...
Writing chests to /Volumes/Ant/MCMaps/an/Map0/chests.js
Outputting block stats to /Volumes/Ant/MCMaps/an/Map0/blockStats.js
Outputted 287 block counts
Outputting world stats to /Volumes/Ant/MCMaps/an/Map0/worldStats.js
Outputted world stats
Finding changed views...
Found 0 changed views (out of 0 total views)
Drawing Day views...
Drawing Night views...
View rendering done!

The texture file 'assets/minecraft/textures/blocks/usb_charger_side.png' could not be found.
Error while parsing blockConfig element: [Solid: null]

Tile cache directory found and is valid. Using cache at /Volumes/Ant/MCMaps/an/Cache/tileHashes/Map0/LayerA
100%
FindChangedTiles took: 0.208 seconds
RenderBaseTiles
Base render is at zoom 23 with 512x512 tiles
RenderBaseTiles
java.lang.NullPointerException of 83)
	at tectonicus.blockTypes.Skull.addEdgeGeometry(Unknown Source)
	at tectonicus.blockTypes.Skull.addInteriorGeometry(Unknown Source)
	at tectonicus.Chunk.createGeometry(Unknown Source)
	at tectonicus.world.World.draw(Unknown Source)
	at tectonicus.world.World.draw(Unknown Source)
	at tectonicus.TileRenderer.renderBaseTiles(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
Cleaning up...
Writing player skin cache info (12 skins to write)
100%
Player skin cache written
Finished
```

Side note, the USB plug is still being requested:
```
The texture file 'assets/minecraft/textures/blocks/usb_charger_side.png' could not be found.
Error while parsing blockConfig element: [Solid: null]
```
[onewaybase.xml.txt](https://github.com/tectonicus/tectonicus/files/681317/onewaybase.xml.txt)

**Comment by skoeven** [comment]
Thanks for all your work looking into this.  I figured out that Mojang started using the newer string ids (e.g. "minecraft:skull") for Entities and TileEntities in the NBT in Minecraft 1.11 so it didn't just break skulls, but signs, paintings, beacons, banners, etc.  Skulls threw an exception because they require the TileEntity information to get the correct textures.

**Comment by turtle2472** [comment]
When will the updated app with this fix implemented be available?  Sorry, I don't mean to pester, just looking forward to having maps again.

**Comment by skoeven** [comment]
A new version is out: [https://github.com/tectonicus/tectonicus/releases/tag/v2.24](https://github.com/tectonicus/tectonicus/releases/tag/v2.24)
You're not pestering, I'm sorry it's taken me so long to get a new version out.  Life has gotten a bit crazy recently and I haven't had much time to work on this.

**Comment by turtle2472** [comment]
I might be the only guy out there who is truly appreciating your work on this but rest assured that I (and the guys on my server) really appreciate you taking the time to keep this alive and working.
