### ISSUE TITLE
`rasteriser type="processing"` still tries to use LWJGL

### ISSUE THREAD

**Issue by ToxicFrog** [tectonicus/tectonicus#89]
```
$ grep -C1 processing tectonicus/config.xml
  <rasteriser
    type="processing"
  />

$ java -jar tectonicus/Tectonicus-2.24.jar config=tectonicus/config.xml
[lots of output elided]
        Headless?: null
        rasteriser:Lwjgl
[...]
Initialising display...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at tectonicus.rasteriser.lwjgl.LwjglRasteriser.<init>(Unknown Source)
        at tectonicus.rasteriser.RasteriserFactory.createRasteriser(Unknown Source)
[...]
Caused by: java.lang.RuntimeException: org.lwjgl.LWJGLException: Could not open X display connection
```

It's unsurprising that it can't initialize X11 since this is a headless machine, but it doesn't seem to be respecting the `<rasteriser type=>` config node either. Setting other rasteriser options like `alphaBits` does work.

**Comment by skoeven** [comment]
I'll look at the configuration parsing code to see if it's working correctly.  Configuration problems aside however, I don't believe either the Processing or the jPCT rasterisers were ever finished by the original developer and I've never touched them at all.
